# Application properties for PokerBank
server.servlet.context-path=/api
server.port=${SERVER_PORT:8080}

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring configuration
spring.application.name=PokerBank
spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}
spring.main.allow-circular-references=true

# Timezone configuration
spring.jackson.time-zone=America/Sao_Paulo

# JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false



# JWT configuration
jwt.secret=${JWT_SECRET_PASSWORD:defaultSecret}
jwt.expiration=${JWT_EXPIRATION_TIME:1440}

# Documentation configuration
springdoc.swagger-ui.path=/documentation
