# 1. Desligue o System.out.println do Hibernate
spring.jpa.show-sql=false

# 2. Ligue o logger do Hibernate no nivel DEBUG
logging.level.org.hibernate.SQL=DEBUG

# 3. Desligue as migrations do flyway em testes para evitar erros com H2
spring.flyway.enabled=false

# 4. Base de dados de teste - deixar o Hibernate criar/derrubar o schema
spring.jpa.hibernate.ddl-auto=create-drop

# 5. Pattern de log
logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%t] [%X{sessionId}] %c{1.} : %msg%n

# 6. Defina o endereço do servidor
server.address=0.0.0.0