# 1. Desligue o System.out.println do Hibernate
spring.jpa.show-sql=false

# 2. Ligue o logger do Hibernate no nivel DEBUG
logging.level.org.hibernate.SQL=DEBUG

# 3. Ligue as migrations do flyway
spring.flyway.enabled=true

# 4. Base de dados de teste
spring.jpa.hibernate.ddl-auto=none

# 5. Pattern de log
logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%t] [%X{sessionId}] %c{1.} : %msg%n

# 6. Defina o endereço do servidor
server.address=0.0.0.0